spring.application.name=KrishiSetu

spring.mongodb.uri=mongodb+srv://prathameshshinde2005_db_user:g3Sv1bobbAUwyLr6@cluster0.on3zgs4.mongodb.net/?appName=Cluster0

spring.mongodb.database=krishiSetu

spring.data.mongodb.auto-index-creation=true